---
title: "Ancom analysis of samples from all visits in AZM arm"
output: html_notebook
author: Regina Esinam Abotsi, Department of Molecular and Cell Biology, University of Cape Town, South Africa
---


```{r}

library(tidyverse)
library(phyloseq)
library("cowplot")
source("ancom_v2.1_reg.R")
```


```{r}
# Read in phyloseq object
trial <- readRDS("breathe_sputum_phyloseq_trial_13Dec2021.RDS")

#Subsets of only AZM

AZM <-subset_samples(trial, trial_arm=="AZM")#441
AZM#441


#Merging at genus level
AZMg<-tax_glom(AZM, taxrank = rank_names(AZM)[6])
taxa_names(AZMg)<-as.character(tax_table(AZMg)[,6])
AZMg


#Filtering
AZM
AZMg
AZMfg <- filter_taxa(AZMg, function(x) sum(x > 0) > (0.005*length(x)), TRUE)   #removing species not seen > 1/2% of samples
AZMfg

```


```{r}
#Repeated measures- Ancom2

#ANCOM-II
#Link https://github.com/FrederickHuangLin/ANCOM


#Preparing otu_data for feature_table for Data preprocessing step
otu_data = as.matrix(AZMfg@otu_table)
otu_data<-as.data.frame(otu_data)


#Preparing meta_data  for Data preprocessing step
meta_data<-as.matrix(sample_data(AZMfg))
meta_data<-as.data.frame(meta_data)
write.csv(meta_data, "res/meta_data_AZM.csv")
#edit im excel so the sample ids have a column heading "SampleID). I have to find a way to do this in R
meta_data<-read.csv("res/meta_data_AZM.csv")
colnames(meta_data)[1]


#Step 1: Data preprocessing

feature_table = otu_data; sample_var = "X"; group_var = "visit"
out_cut = 0.05; zero_cut = 0.90; lib_cut = 0; neg_lb = TRUE

prepro = feature_table_pre_process(feature_table, meta_data, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)

feature_table = prepro$feature_table # Preprocessed feature table
meta_data = prepro$meta_data # Preprocessed metadata
struc_zero = prepro$structure_zeros # Structural zero info

# Step 2: ANCOM
main_var = "visit"; p_adj_method = "BH"; alpha = 0.05
adj_formula = NULL; rand_formula = "~ 1 | studyno"
control = lmeControl(maxIter = 100, msMaxIter = 100, opt = "optim")
t_start = Sys.time()
res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            alpha, adj_formula, rand_formula, control = control)
t_end = Sys.time()
t_run = t_end - t_start # around 2mins

res
write_csv(res$out, "res/res_AZM_allvisit.csv")
write_csv(res$dat, "res/res_AZM_mean_clr1.csv")
```



```{r, Plotting taxa}
# Step 3: Volcano Plot

# Number of taxa except structural zeros
n_taxa = ifelse(is.null(struc_zero), nrow(feature_table), sum(apply(struc_zero, 1, sum) == 0))
# Cutoff values for declaring differentially abundant taxa
cut_off = c(0.9 * (n_taxa -1), 0.8 * (n_taxa -1), 0.7 * (n_taxa -1), 0.6 * (n_taxa -1))
names(cut_off) = c("detected_0.9", "detected_0.8", "detected_0.7", "detected_0.6")

# Annotation data
dat_ann = data.frame(x = min(res$fig$data$x), y = cut_off["detected_0.6"], label = "W[0.6]")

```


```{r}
fig = res$fig + 
  geom_hline(yintercept = cut_off["detected_0.6"], linetype = "dashed") + 
  geom_text(data = dat_ann, aes(x = x, y = y, label = label), 
            size = 4, vjust = -0.5, hjust = 0, color = "orange", parse = TRUE)
fig 
```



```{r, Differentially abundant taxa detected by ANCOM-II}
ancom_res<-data.frame(res$out)
ancom_da<-ancom_res %>% 
  filter(detected_0.6==TRUE)
ancom_da$taxa_id #0
write.csv(ancom_da, "res/daAZM_allvisits.csv")


```









