---
title: "Linear Mixed effect modelling of relative abundance of selected genera and covariates"
output: html_notebook
date: "30th December 2021"
Author: Regina Esinam Abotsi, Departmemt of Molecular and Cell Biology, University of Cape Town, South Africa 
---


```{r}
library(tidyverse)
library(phyloseq)
library(lme4)
library(lmerTest)
library(gplots)
library(vegan)
library(dplyr)
library(microbiome)
```

```{r, Importing and subsetting data}
#-----Part1----------------------
trial <- readRDS("data/breathe_sputum_phyloseq_trial_13Dec2021.RDS")
trial

#Merging at Genus level

trialg<-tax_glom(trial, taxrank = rank_names(trial)[6])
taxa_names(trialg)<-as.character(tax_table(trialg)[,6])
trialg


#Filtering
trial
trialg
trialfg <- filter_taxa(trialg, function(x) sum(x > 0) > (0.005*length(x)), TRUE)   #removing species not seen > 1/2% of samples
trialfg

```

#Preprocessing and subsetting data
```{r}
#Convert to percentage relative abundances
trialfg_rel1 = phyloseq::transform_sample_counts(trialfg,function(x){(x / sum(x))*100})
#all = subset_taxa(trialfg_rel, Genus=="Moraxella" | Genus=="Haemophilus"| Genus=="Staphylococcus"| Genus=="Streptococcus"|Genus=="Streptococcus"| Genus=="Pseudomonas" )

all = subset_taxa(trialfg_rel1, Genus=="Moraxella" | Genus=="Haemophilus"| Genus=="Prevotella"|
                    Genus=="Streptococcus"|Genus=="Neisseria" )

mdf<-psmelt(all)
str(mdf)

# converting relevant variables to factors
names <- c( 'f24mrcscore','f24mrcscore_baseline','f14adm_baseline', "f15nadm_baseline", 'f16tbtreat_baseline')
mdf[ , names] <- lapply(mdf[ , names], factor)
str(mdf)

#-------------------Releveling so that  other levels  can be used as reference---------------------
mdf <- within(mdf, agegpenrl_baseline <- relevel(agegpenrl_baseline, ref = "d17-19y"))
mdf <- within(mdf, abnrr <- relevel(abnrr, ref = "Not abnormal"))
mdf <- within(mdf, abnsat <- relevel(abnsat, ref = "Not abnormal"))
mdf <- within(mdf, abnhr <- relevel(abnhr, ref = "Not abnormal"))
mdf <- within(mdf, vlenrlsup_baseline <- relevel(vlenrlsup_baseline, ref = "Supressed"))
mdf <- within(mdf, normalhaz_baseline <- relevel(normalhaz_baseline, ref = ">=-2"))
mdf <- within(mdf, normalwaz_baseline <- relevel(normalwaz_baseline, ref = ">=-2"))


#mdf has 5 genera. Lets split per genera
mcn<-filter(mdf, OTU=="Moraxella")
hmn<-filter(mdf, OTU=="Haemophilus")
pvn<-filter(mdf, OTU=="Prevotella")
spn<-filter(mdf, OTU=="Streptococcus")
nen<-filter(mdf, OTU=="Neisseria")


#-------------------Releveling so that Placebo  can be used as reference---------------------
mdf2 <- within(mdf, trial_arm <- relevel(trial_arm, ref = "Placebo"))

#mdf has 5 genera. Lets split per genera
mcn2<-filter(mdf2, OTU=="Moraxella")
hmn2<-filter(mdf2, OTU=="Haemophilus")
pvn2<-filter(mdf2, OTU=="Prevotella")
spn2<-filter(mdf2, OTU=="Streptococcus")
nen2<-filter(mdf2, OTU=="Neisseria")

colnames(mdf2)

```




#STreptococcus
```{r}
#AZM as reference
lmer_sp <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload","vlenrlsup_baseline","normalwaz_baseline", "normalhaz_baseline", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = spn)
                   summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_sp, function(x) write.table( data.frame(x), 'results/lmer_results_streptococcus_allfinal_AZMref.csv'  , append= T, sep=',' ))
```

```{r}
#Placebo as reference
lmer_sp <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload","vlenrlsup_baseline","normalwaz_baseline", "normalhaz_baseline", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = spn2)
                   summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_sp, function(x) write.table( data.frame(x), 'results/lmer_results_streptococcus_allfinalPlacebo_ref.csv'  , append= T, sep=',' ))
```

#Multivariate analysis
```{r}
#AZM as reference
  md2 <- lmer(Abundance ~ trial_arm*visit + 
                +adherence+site +agegpenrl_baseline +sex +colmonthgp_mal2 +f24mrcscore_baseline+fev1z+normalhaz_baseline+hospitalised12m+f11cotri_baseline
                +duryartgp_baseline+vlenrlsup_baseline+
                artdrug2ndline_baseline+f14adm_baseline+f16tbtreat_baseline+ageyart_baseline+
              (1|studyno),
              data = spn)
                  summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
                   write.csv(table3, "results/strep_LME_multivariate21122021finalAZMref.csv")   
```


```{r}
#Placebo as reference
  md2 <- lmer(Abundance ~ trial_arm*visit + 
                +adherence+site +agegpenrl_baseline +sex +colmonthgp_mal2 +f24mrcscore_baseline+fev1z+normalhaz_baseline+hospitalised12m+f11cotri_baseline
                +duryartgp_baseline+vlenrlsup_baseline+
                artdrug2ndline_baseline+f14adm_baseline+f16tbtreat_baseline+ageyart_baseline+
              (1|studyno),
              data = spn2)
                  summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
                   write.csv(table3, "results/strep_LME_multivariate21122021finalPlaceboRef.csv")   
```


#Obtaining  p values for multi-level factors/variables
```{r}
anova(md2)
```





#Prevotella
```{r}
#AZM as reference
lmer_pv <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = pvn)
                  summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_pv, function(x) write.table( data.frame(x), 'results/lmer_results_prevotella_allfinalAZMref.csv'  , append= T, sep=',' ))
```

```{r}
#Placebo as reference
lmer_pv <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = pvn2)
                  summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_pv, function(x) write.table( data.frame(x), 'results/lmer_results_prevotella_allfinalPlaRef.csv'  , append= T, sep=',' ))
```

#Multivariate analysis

```{r}
#AZM as reference
 md2 <- lmer(Abundance ~ trial_arm*visit +adherence+site+agegpenrl_baseline+sex+colmonthgp_mal2 +f24mrcscore_baseline+fev1z+ normalhaz_baseline+ acut_exac12m +f11cotri_baseline+duryartgp_baseline+ vlenrlsup_baseline+artdrug2ndline_baseline+  f14adm_baseline+f16tbtreat_baseline+ageyart_baseline+
                (1|studyno),
              data = pvn2)
                   summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
  write.csv(table3, "results/prevotella_multi_genusAZM_ref.csv")    
```


```{r}
#Placebo as reference
 md2 <- lmer(Abundance ~ trial_arm*visit +adherence+site+agegpenrl_baseline+sex+colmonthgp_mal2 +f24mrcscore_baseline+fev1z+ normalhaz_baseline+ acut_exac12m +f11cotri_baseline+duryartgp_baseline+ vlenrlsup_baseline+artdrug2ndline_baseline+  f14adm_baseline+f16tbtreat_baseline+ageyart_baseline+
                (1|studyno),
              data = pvn2)
                   summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
  write.csv(table3, "results/prevotella_multi_genusPlacRef.csv")    
```



#Haemophilus
```{r}
#AZM as reference
lmer_hm <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat","vlenrlsup_baseline", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = hmn)
                   summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_hm, function(x) write.table( data.frame(x), 'results/lmer_results_haemophilus_allfinalAZMRef.csv'  , append= T, sep=',' ))
```



```{r}
#Placebo as reference
lmer_hm <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat","vlenrlsup_baseline", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = hmn2)
                   summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_hm, function(x) write.table( data.frame(x), 'results/lmer_results_haemophilus_allfinalPlacRef.csv'  , append= T, sep=',' ))
```


             


#Multivariate analysis

```{r}
#AZM as reference
 md2 <- lmer(Abundance ~ trial_arm*visit +adherence+site+agegpenrl_baseline+sex+colmonthgp_mal2 +f24mrcscore_baseline+fev1z+ normalhaz_baseline+ acut_exac12m +f11cotri_baseline+duryartgp_baseline+abnhr+ vlenrlsup_baseline+artdrug2ndline_baseline+  f14adm_baseline+  f16tbtreat_baseline+ageyart_baseline+ (1|studyno),
              data = hmn)
                summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
 write.csv(table3, "results/haem_multi_genusAZMRef.csv")   
```


```{r}
#Placebo as reference
 md2 <- lmer(Abundance ~ trial_arm*visit +adherence+site+agegpenrl_baseline+sex+colmonthgp_mal2 +f24mrcscore_baseline+fev1z+ normalhaz_baseline+ acut_exac12m +f11cotri_baseline+duryartgp_baseline+abnhr+ vlenrlsup_baseline+artdrug2ndline_baseline+  f14adm_baseline+  f16tbtreat_baseline+ageyart_baseline+ (1|studyno),
              data = hmn2)
                summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
 write.csv(table3, "results/haem_multi_genusPlacRef.csv")   
```


#Moraxella
```{r}
#AZM as reference
lmer_mc <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat","normalhaz_baseline", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","vlenrlsup_baseline", "f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = mcn)
                    summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_mc, function(x) write.table( data.frame(x), 'results/lmer_results_moraxella_allfinalAZmRef.csv'  , append= T, sep=',' ))
```


```{r}
#Placebo as reference
lmer_mc <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat","normalhaz_baseline", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","vlenrlsup_baseline", "f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = mcn2)
                    summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_mc, function(x) write.table( data.frame(x), 'results/lmer_results_moraxella_allfinalPlacRef.csv'  , append= T, sep=',' ))
```


             

#Multivariate analysis
```{r}
#AZM as reference
 md2 <- lmer(Abundance ~ trial_arm*visit + adherence+site+agegpenrl_baseline+sex+colmonthgp_mal2 +f24mrcscore_baseline+fev1z+ normalhaz_baseline+ acut_exac12m + f11cotri_baseline+duryartgp_baseline+abnsat+vlenrlsup_baseline+
               artdrug2ndline_baseline+  f14adm_baseline+f16tbtreat_baseline+ +ageyart_baseline+(1|studyno),
              data = mcn)
                    summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
  write.csv(table3, "results/morax_multi_genusAZMref.csv")   
```



```{r}
#Placebo as reference
 md2 <- lmer(Abundance ~ trial_arm*visit + adherence+site+agegpenrl_baseline+sex+colmonthgp_mal2 +f24mrcscore_baseline+fev1z+ normalhaz_baseline+ acut_exac12m + f11cotri_baseline+duryartgp_baseline+abnsat+vlenrlsup_baseline+
               artdrug2ndline_baseline+  f14adm_baseline+f16tbtreat_baseline+ +ageyart_baseline+(1|studyno),
              data = mcn2)
                    summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
  write.csv(table3, "results/morax_multi_genusPlacRef.csv")   
```




#Neisseria

```{r}
#AZM as reference
lmer_ne <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat", "vlenrlsup_baseline", "normalhaz_baseline", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = nen)
                    summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_ne, function(x) write.table( data.frame(x), 'results/lmer_results_neisseria_allfinalAZMref.csv'  , append= T, sep=',' ))
```



```{r}
#Placebo as reference
lmer_ne <-lapply(c("trial_arm","visit","adherence","site", "agey", "sex","colmonthgp_mal2" ,"f24mrcscore_baseline ","fev1z","FVC", "FVCZ", "FEV1FVCZ","FVCpcpred", "FEVpcpred","zbmiuk","zwauk", "zhauk", "cd4", "vload", "acut_exac12m", "hospitalised12m" , " antibiotic12m" , "any3_reasons.1",   "f11cotri_baseline","agegpenrl_baseline","duryartgp_baseline", "abnrr", "abnsat", "vlenrlsup_baseline", "normalhaz_baseline", "abnhr","cd4enrl_baseline","vlenrl_baseline","artdrug1stline_baseline","artdrug2ndline_baseline", "artreg_baseline","f14adm_baseline",  "f16tbtreat_baseline", "ageyart_baseline", "duryart_baseline", " cd4gp_baseline", "agegpsym_baseline") ,
                 
                 function(var) {
                   
                   formula    <- as.formula(paste("Abundance ~ trial_arm*visit + (1|studyno)+", var))
                   md1 <- lmer(formula, data = nen2)
                    summary(md1)
                   beta <- round(fixef(md1),2)
                   CI <- round(confint(md1, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md1))[,'Pr(>|t|)'],2)
                   table2 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table2
                 })
lapply(lmer_ne, function(x) write.table( data.frame(x), 'results/lmer_results_neisseria_allfinalPlacRef.csv'  , append= T, sep=',' ))
```




#Multivariate analysis
```{r}
#AZM as reference
 md2 <- lmer(Abundance ~ trial_arm*visit +adherence+site+agegpenrl_baseline+sex+colmonthgp_mal2 +f24mrcscore_baseline+fev1z+ normalhaz_baseline+ acut_exac12m 
             + f11cotri_baseline+duryartgp_baseline+abnhr+ vlenrlsup_baseline+artdrug2ndline_baseline+  f14adm_baseline+f16tbtreat_baseline+ageyart_baseline+ (1|studyno),
              data = nen)
                    summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
  write.csv(table3, "results/neisseria_multi_genusAZMref.csv")   
```

```{r}
#Placebo as reference
 md2 <- lmer(Abundance ~ trial_arm*visit +adherence+site+agegpenrl_baseline+sex+colmonthgp_mal2 +f24mrcscore_baseline+fev1z+ normalhaz_baseline+ acut_exac12m 
             + f11cotri_baseline+duryartgp_baseline+abnhr+ vlenrlsup_baseline+artdrug2ndline_baseline+  f14adm_baseline+f16tbtreat_baseline+ageyart_baseline+ (1|studyno),
              data = nen2)
                    summary(md2)
                   beta <- round(fixef(md2),2)
                   CI <- round(confint(md2, level = 0.95),2)
                   CI <- CI[-(1:2),]
                   pvalue<-round(coef(summary(md2))[,'Pr(>|t|)'],2)
                   table3 <- as.data.frame(cbind(beta, CI, pvalue))# Bind columns together as dataset
                   table3
  write.csv(table3, "results/neisseria_multi_genusPlacRef.csv")   
```




