---
title: "Regression analysis for within-patient change in beta diversity and lung fuction "
output: html_notebook
date: "24th December 2021"
Author: Regina Esinam Abotsi, Department of Molecular and Cell Biology, University of Cape Town, South Africa
---

```{r}
library(tidyverse)
```


#PART 1

#ASSOCIATION BETWEEN CHANGE IN  AITCHISON'S DISTANCE  AND CHANGE IN LUNG FUNCTION METRICS FVCZ, FEV1/FVCZ, FEV1z, FVC, FEV1/FVC
```{r}
betaFVC<-read.csv("data/all_within_patient_change_data2ndDec2021.csv", stringsAsFactors = TRUE)

str(betaFVC)
```






Stratify data into AZM and Placebo

```{r}
#------Stratify data into AZM and Placebo-------------------------
t_plac<-betaFVC%>%
  filter(trial_arm=="Placebo")
t_azm<-betaFVC%>%
  filter(trial_arm=="AZM")



#------Stratify data into each time interval within the AZM and Placebo-------

#Placebo
T1T2pl<-betaFVC%>%
  filter(interval =="T1 vs T2",
         trial_arm=="Placebo")

T2T3pl<-betaFVC%>%
  filter(interval =="T2 vs T3",
         trial_arm=="Placebo")

T1T3pl<-betaFVC%>%
  filter(interval =="T1 vs T3",
         trial_arm=="Placebo")

#AZM

T1T2az<-betaFVC%>%
  filter(interval =="T1 vs T2",
         trial_arm=="AZM")

T2T3az<-betaFVC%>%
  filter(interval =="T2 vs T3",
         trial_arm=="AZM")

T1T3az<-betaFVC%>%
  filter(interval =="T1 vs T3",
         trial_arm=="AZM")
```

```{r}
#number of participants in each group
#all
length(unique(betaFVC$Studyno))

#trial arms
length(unique(t_plac$Studyno))
length(unique(t_azm$Studyno))


```


#Conduct univariate regression to detect association between change in FEV1z  and FVCZ and change in beta diversity

#-----------------------------------------FEV1Z---------------------------------------------------------------
```{r}
#AZM as reference
   reg <- lm(diff_euclidean~diff_FEV1z*trial_arm, data = betaFVC)
                   summary(reg)
                   confint(reg, level = 0.95)
              
```

```{r}
#Placebo as reference
betaFVC2<-betaFVC
betaFVC2 <- within(betaFVC2, trial_arm <- relevel(trial_arm, ref = "Placebo"))
   reg <- lm(diff_euclidean~diff_FEV1z*trial_arm, data = betaFVC2)
                   summary(reg)
                   confint(reg, level = 0.95)
```

```{r}
#title for section
x <- "AZM as reference - FEV1z"
class(x)
write.table( x, 'results/change_aitchison_lung_function24122021ALL.csv'  , append= T, sep=',' )

#association between change in FEV1z(diff_FEV1z) and change in Aitchison distance in all data (both trial arm)
reg<-lm (diff_euclidean~diff_FEV1z*trial_arm, data=betaFVC)
                   summary(reg)
                   bet <- round(coef(reg), 2)# Prepare the columns
                   CI <- round(confint(reg, level = 0.95),2)
                   pvalue<-round(coef(summary(reg))[,'Pr(>|t|)'],3)
                   table2 <- as.data.frame(cbind(bet, CI, pvalue))# Bind columns together as dataset
                   table2
write.table( table2, 'results/change_aitchison_lung_function24122021ALL.csv'  , append= T, sep=',' )

```


```{r}
#title for section
x <- "Placebo  as reference - FEV1z"
class(x)
write.table( x, 'results/change_aitchison_lung_function24122021ALL.csv'  , append= T, sep=',' )

#association between change in FEV1z(diff_FEV1z) and change in Aitchison distance in all data (both trial arm)
reg<-lm (diff_euclidean~diff_FEV1z*trial_arm, data=betaFVC2)
                   summary(reg)
                   bet <- round(coef(reg), 2)# Prepare the columns
                   CI <- round(confint(reg, level = 0.95),2)
                   pvalue<-round(coef(summary(reg))[,'Pr(>|t|)'],3)
                   table2 <- as.data.frame(cbind(bet, CI, pvalue))# Bind columns together as dataset
                   table2
write.table( table2, 'results/change_aitchison_lung_function24122021ALL.csv'  , append= T, sep=',' )

```



```{r}
#title for section
x <- "AZM as reference - FVCz"
class(x)
write.table( x, 'results/change_aitchison_lung_function24122021ALL.csv'  , append= T, sep=',' )

#association between change in FVCZ(dif_FVCZ) and change in Aitchison distance in all data (both trial arm)
reg<-lm (diff_euclidean~dif_FVCZ*trial_arm, data=betaFVC)
                   summary(reg)
                   bet <- round(coef(reg), 2)# Prepare the columns
                   CI <- round(confint(reg, level = 0.95),2)
                   pvalue<-round(coef(summary(reg))[,'Pr(>|t|)'],3)
                   table2 <- as.data.frame(cbind(bet, CI, pvalue))# Bind columns together as dataset
                   table2
write.table( table2, 'results/change_aitchison_lung_function24122021ALL.csv'  , append= T, sep=',' )

```


```{r}
#title for section
x <- "Placebo  as reference - FVCz"
class(x)
write.table( x, 'results/change_aitchison_lung_function24122021ALL.csv'  , append= T, sep=',' )

#association between change in FVCZ(dif_FVCZ) and change in Aitchison distance in all data (both trial arm)
reg<-lm (diff_euclidean~dif_FVCZ*trial_arm, data=betaFVC2)
                   summary(reg)
                   bet <- round(coef(reg), 2)# Prepare the columns
                   CI <- round(confint(reg, level = 0.95),2)
                   pvalue<-round(coef(summary(reg))[,'Pr(>|t|)'],3)
                   table2 <- as.data.frame(cbind(bet, CI, pvalue))# Bind columns together as dataset
                   table2
write.table( table2, 'results/change_aitchison_lung_function24122021ALL.csv'  , append= T, sep=',' )

```










